CREATE TABLE IF NOT EXISTS `paymeforyou`.`merchant` (
  `id` int NOT NULL AUTO_INCREMENT,
  `merchant_name` varchar(30) NOT NULL,
  `company_name` varchar(30) NOT NULL,
  `affiliate_id` int DEFAULT NULL,
  `settlement_method` enum('NO_SETTLEMENT','SEAMLESS','MONTHLY') NOT NULL,
  `fundin_commission_rate` decimal(5,2) NOT NULL,
  `fundin_min_amt` decimal(20,2) NOT NULL,
  `fundin_max_amt` decimal(20,2) NOT NULL,
  `fundout_commission_rate` decimal(5,2) NOT NULL,
  `fundout_min_amt` decimal(20,2) NOT NULL,
  `fundout_max_amt` decimal(20,2) NOT NULL,
  `currency` enum('Rupiah') NOT NULL,
  `balance` decimal(30,2) NOT NULL,
  `status` tinyint NOT NULL,
  `open_bank_fundin_api` tinyint NOT NULL,
  `open_bank_fundout_api` tinyint NOT NULL,
  `merchant_code` varchar(30) DEFAULT NULL,
  `secret_key` text,
  `notification_url` varchar(200) DEFAULT NULL,
  `ip_white_list` text,
  `created_by` varchar(30) NOT NULL,
  `created_time` timestamp(6) NOT NULL,
  `updated_by` varchar(30),
  `updated_time` timestamp(6),
  PRIMARY KEY (`id`),
  KEY `fk_merchant_affiliate_idx` (`affiliate_id`),
  CONSTRAINT `fk_merchant_affiliate` FOREIGN KEY (`affiliate_id`) REFERENCES `affiliate` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='merchant info';